[tool.ruff]
extend-exclude = [".venv", ".venv_dev", ".venv_minimal", "build", "dist", ".git", "node_modules"]
line-length = 88
select = ["E", "F", "W", "I", "C", "UP", "A"]
extend-ignore = ["E203", "W503"]
